from PyQt5 import QtGui

FG_COLOR = QtGui.QColor('black')
BG_COLOR = QtGui.QColor('white')
SELECTED_COLOR = QtGui.QColor('blue')

PITCH_LINE_SEP = 6
BARLINE_FRONT_PAD = 25
BARLINE_REAR_PAD = 25

STAFF_X_PAD = 20
STAFF_Y_PAD = 10 * PITCH_LINE_SEP
STAFF_GROUP_Y_PAD = 5 * PITCH_LINE_SEP
